import Ember from 'ember';

export default Ember.Route.extend({
	model : function (params) {
		return this.store.find('product', params.productId);
	}


	// model()  {
	// 	return {
	// 		"productId":"5881102",
	// 		"name":"Big Icon Polo",
	// 		"collection":"99553",
	// 		"longDesc":"Supersoft with a timeless design, featuring a contrast icon at left chest, interior neck taping and side slits, an asymmetrical hem, Muscle Fit, Imported<br><br>100% Cotton",
	// 		"shortDesc":"",
	// 		"isGiftCard":false,
	// 		"ofpImage":"1",
	// 		"modelBackground":"default",
	// 		"priceFlag":"1",
	// 		"crossSellProductIds":[  

	// 		],
	// 		"sizeChartSeq":"6",
	// 		"displaySoldOut":false,
	// 		"published":false,
	// 		"lowPrice":0,
	// 		"lowPriceFmt":"$0.00",
	// 		"highPrice":0,
	// 		"highPriceFmt":"$0.00",
	// 		"lowListPrice":0,
	// 		"lowListPriceFmt":"$0.00",
	// 		"highListPrice":0,
	// 		"highListPriceFmt":"$0.00",
	// 		"swatchAttrId":"Color",
	// 		"defaultSwatchSequence":"01",
	// 		"swatchSequences":[  
	// 			"01",
	// 			"03",
	// 			"02"
	// 		],
	// 		"swatchSequencesExcludeSoldOut":[  

	// 		],
	// 		"productAttrs":{  
	// 			"gender":"male",
	// 			"fullScreenControl":"false",
	// 			"volumeControl":"false",
	// 			"clubExclusive":"false",
	// 			"productType":"Standard",
	// 			"emailCapture":"false",
	// 			"productSoldOut":"false",
	// 			"popinsEligibility":"eligible",
	// 			"risEligibility":"eligibleNoShip",
	// 			"OFPModelSize":"M",
	// 			"videoControls":"false",
	// 			"maxPurchaseQty":2,
	// 			"OFPModelHeight":"6'1&quot;",
	// 			"fisEligibility":"eligible",
	// 			"sizechart":"6"
	// 		},
	// 		"productAttrsComplex":{  

	// 		},
	// 		"items":[  
	// 			{  
	// 				"itemId":"5881658",
	// 				"shortSku":"618955482",
	// 				"longSku":"121-224-0645-200",
	// 				"prodImg":"99553_01",
	// 				"swatchSequence":"01",
	// 				"listPrice":50,
	// 				"listPriceFmt":"$50.00",
	// 				"offerPrice":50,
	// 				"offerPriceFmt":"$50.00",
	// 				"taxItemType":"CLT",
	// 				"definingAttrs":{  
	// 					"Size":{  
	// 						"name":"Size",
	// 						"description":"Size",
	// 						"value":"M",
	// 						"sequence":90,
	// 						"valueSequence":6
	// 					},
	// 					"Color":{  
	// 						"name":"Color",
	// 						"description":"Color",
	// 						"value":"NAVY",
	// 						"sequence":1,
	// 						"valueSequence":0
	// 					},
	// 					"Size_Grp_1_P":{  
	// 						"name":"Size_Grp_1_P",
	// 						"description":"Size",
	// 						"value":"M",
	// 						"sequence":0,
	// 						"valueSequence":4
	// 					}
	// 				},
	// 				"descriptiveAttrs":{  

	// 				},
	// 				"inventory":{  
	// 					"inventoryStatus":"Unavailable",
	// 					"inventory":0,
	// 					"published":true
	// 				},
	// 				"priceFlag":"1"
	// 			},
	// 			{  
	// 				"itemId":"5881659",
	// 				"shortSku":"618965496",
	// 				"longSku":"121-224-0645-200",
	// 				"prodImg":"99553_01",
	// 				"swatchSequence":"01",
	// 				"listPrice":50,
	// 				"listPriceFmt":"$50.00",
	// 				"offerPrice":50,
	// 				"offerPriceFmt":"$50.00",
	// 				"taxItemType":"CLT",
	// 				"definingAttrs":{  
	// 					"Size":{  
	// 						"name":"Size",
	// 						"description":"Size",
	// 						"value":"L",
	// 						"sequence":110,
	// 						"valueSequence":8
	// 					},
	// 					"Color":{  
	// 						"name":"Color",
	// 						"description":"Color",
	// 						"value":"NAVY",
	// 						"sequence":1,
	// 						"valueSequence":0
	// 					},
	// 					"Size_Grp_1_P":{  
	// 						"name":"Size_Grp_1_P",
	// 						"description":"Size",
	// 						"value":"L",
	// 						"sequence":0,
	// 						"valueSequence":5
	// 					}
	// 				},
	// 				"descriptiveAttrs":{  

	// 				},
	// 				"inventory":{  
	// 					"inventoryStatus":"Unavailable",
	// 					"inventory":0,
	// 					"published":true
	// 				},
	// 				"priceFlag":"1"
	// 			},
	// 			{  
	// 				"itemId":"5881660",
	// 				"shortSku":"618965509",
	// 				"longSku":"121-224-0645-200",
	// 				"prodImg":"99553_01",
	// 				"swatchSequence":"01",
	// 				"listPrice":50,
	// 				"listPriceFmt":"$50.00",
	// 				"offerPrice":50,
	// 				"offerPriceFmt":"$50.00",
	// 				"taxItemType":"CLT",
	// 				"definingAttrs":{  
	// 					"Size":{  
	// 						"name":"Size",
	// 						"description":"Size",
	// 						"value":"XL",
	// 						"sequence":130,
	// 						"valueSequence":10
	// 					},
	// 					"Color":{  
	// 						"name":"Color",
	// 						"description":"Color",
	// 						"value":"NAVY",
	// 						"sequence":1,
	// 						"valueSequence":0
	// 					},
	// 					"Size_Grp_1_P":{  
	// 						"name":"Size_Grp_1_P",
	// 						"description":"Size",
	// 						"value":"XL",
	// 						"sequence":0,
	// 						"valueSequence":6
	// 					}
	// 				},
	// 				"descriptiveAttrs":{  

	// 				},
	// 				"inventory":{  
	// 					"inventoryStatus":"Unavailable",
	// 					"inventory":0,
	// 					"published":true
	// 				},
	// 				"priceFlag":"1"
	// 			},
	// 			{  
	// 				"itemId":"5881661",
	// 				"shortSku":"618965517",
	// 				"longSku":"121-224-0645-200",
	// 				"prodImg":"99553_01",
	// 				"swatchSequence":"01",
	// 				"listPrice":50,
	// 				"listPriceFmt":"$50.00",
	// 				"offerPrice":50,
	// 				"offerPriceFmt":"$50.00",
	// 				"taxItemType":"CLT",
	// 				"definingAttrs":{  
	// 					"Size":{  
	// 						"name":"Size",
	// 						"description":"Size",
	// 						"value":"XXL",
	// 						"sequence":150,
	// 						"valueSequence":12
	// 					},
	// 					"Color":{  
	// 						"name":"Color",
	// 						"description":"Color",
	// 						"value":"NAVY",
	// 						"sequence":1,
	// 						"valueSequence":0
	// 					},
	// 					"Size_Grp_1_P":{  
	// 						"name":"Size_Grp_1_P",
	// 						"description":"Size",
	// 						"value":"XXL",
	// 						"sequence":0,
	// 						"valueSequence":7
	// 					}
	// 				},
	// 				"descriptiveAttrs":{  

	// 				},
	// 				"inventory":{  
	// 					"inventoryStatus":"Unavailable",
	// 					"inventory":0,
	// 					"published":true
	// 				},
	// 				"priceFlag":"1"
	// 			},
	// 			{  
	// 				"itemId":"5881662",
	// 				"shortSku":"618965525",
	// 				"longSku":"121-224-0645-500",
	// 				"prodImg":"99553_03",
	// 				"swatchSequence":"03",
	// 				"listPrice":50,
	// 				"listPriceFmt":"$50.00",
	// 				"offerPrice":50,
	// 				"offerPriceFmt":"$50.00",
	// 				"taxItemType":"CLT",
	// 				"definingAttrs":{  
	// 					"Size":{  
	// 						"name":"Size",
	// 						"description":"Size",
	// 						"value":"XXL",
	// 						"sequence":150,
	// 						"valueSequence":12
	// 					},
	// 					"Color":{  
	// 						"name":"Color",
	// 						"description":"Color",
	// 						"value":"RED",
	// 						"sequence":3,
	// 						"valueSequence":0
	// 					},
	// 					"Size_Grp_1_P":{  
	// 						"name":"Size_Grp_1_P",
	// 						"description":"Size",
	// 						"value":"XXL",
	// 						"sequence":0,
	// 						"valueSequence":7
	// 					}
	// 				},
	// 				"descriptiveAttrs":{  

	// 				},
	// 				"inventory":{  
	// 					"inventoryStatus":"Unavailable",
	// 					"inventory":0,
	// 					"published":true
	// 				},
	// 				"priceFlag":"1"
	// 			},
	// 			{  
	// 				"itemId":"5881663",
	// 				"shortSku":"618965533",
	// 				"longSku":"121-224-0645-500",
	// 				"prodImg":"99553_03",
	// 				"swatchSequence":"03",
	// 				"listPrice":50,
	// 				"listPriceFmt":"$50.00",
	// 				"offerPrice":50,
	// 				"offerPriceFmt":"$50.00",
	// 				"taxItemType":"CLT",
	// 				"definingAttrs":{  
	// 					"Size":{  
	// 						"name":"Size",
	// 						"description":"Size",
	// 						"value":"S",
	// 						"sequence":50,
	// 						"valueSequence":4
	// 					},
	// 					"Color":{  
	// 						"name":"Color",
	// 						"description":"Color",
	// 						"value":"RED",
	// 						"sequence":3,
	// 						"valueSequence":0
	// 					},
	// 					"Size_Grp_1_P":{  
	// 						"name":"Size_Grp_1_P",
	// 						"description":"Size",
	// 						"value":"S",
	// 						"sequence":0,
	// 						"valueSequence":3
	// 					}
	// 				},
	// 				"descriptiveAttrs":{  

	// 				},
	// 				"inventory":{  
	// 					"inventoryStatus":"Unavailable",
	// 					"inventory":0,
	// 					"published":true
	// 				},
	// 				"priceFlag":"1"
	// 			},
	// 			{  
	// 				"itemId":"5881664",
	// 				"shortSku":"618965541",
	// 				"longSku":"121-224-0645-500",
	// 				"prodImg":"99553_03",
	// 				"swatchSequence":"03",
	// 				"listPrice":50,
	// 				"listPriceFmt":"$50.00",
	// 				"offerPrice":50,
	// 				"offerPriceFmt":"$50.00",
	// 				"taxItemType":"CLT",
	// 				"definingAttrs":{  
	// 					"Size":{  
	// 						"name":"Size",
	// 						"description":"Size",
	// 						"value":"M",
	// 						"sequence":90,
	// 						"valueSequence":6
	// 					},
	// 					"Color":{  
	// 						"name":"Color",
	// 						"description":"Color",
	// 						"value":"RED",
	// 						"sequence":3,
	// 						"valueSequence":0
	// 					},
	// 					"Size_Grp_1_P":{  
	// 						"name":"Size_Grp_1_P",
	// 						"description":"Size",
	// 						"value":"M",
	// 						"sequence":0,
	// 						"valueSequence":4
	// 					}
	// 				},
	// 				"descriptiveAttrs":{  

	// 				},
	// 				"inventory":{  
	// 					"inventoryStatus":"Unavailable",
	// 					"inventory":0,
	// 					"published":true
	// 				},
	// 				"priceFlag":"1"
	// 			},
	// 			{  
	// 				"itemId":"5881665",
	// 				"shortSku":"618965550",
	// 				"longSku":"121-224-0645-500",
	// 				"prodImg":"99553_03",
	// 				"swatchSequence":"03",
	// 				"listPrice":50,
	// 				"listPriceFmt":"$50.00",
	// 				"offerPrice":50,
	// 				"offerPriceFmt":"$50.00",
	// 				"taxItemType":"CLT",
	// 				"definingAttrs":{  
	// 					"Size":{  
	// 						"name":"Size",
	// 						"description":"Size",
	// 						"value":"L",
	// 						"sequence":110,
	// 						"valueSequence":8
	// 					},
	// 					"Color":{  
	// 						"name":"Color",
	// 						"description":"Color",
	// 						"value":"RED",
	// 						"sequence":3,
	// 						"valueSequence":0
	// 					},
	// 					"Size_Grp_1_P":{  
	// 						"name":"Size_Grp_1_P",
	// 						"description":"Size",
	// 						"value":"L",
	// 						"sequence":0,
	// 						"valueSequence":5
	// 					}
	// 				},
	// 				"descriptiveAttrs":{  

	// 				},
	// 				"inventory":{  
	// 					"inventoryStatus":"Unavailable",
	// 					"inventory":0,
	// 					"published":true
	// 				},
	// 				"priceFlag":"1"
	// 			},
	// 			{  
	// 				"itemId":"5881666",
	// 				"shortSku":"618965568",
	// 				"longSku":"121-224-0645-500",
	// 				"prodImg":"99553_03",
	// 				"swatchSequence":"03",
	// 				"listPrice":50,
	// 				"listPriceFmt":"$50.00",
	// 				"offerPrice":50,
	// 				"offerPriceFmt":"$50.00",
	// 				"taxItemType":"CLT",
	// 				"definingAttrs":{  
	// 					"Size":{  
	// 						"name":"Size",
	// 						"description":"Size",
	// 						"value":"XL",
	// 						"sequence":130,
	// 						"valueSequence":10
	// 					},
	// 					"Color":{  
	// 						"name":"Color",
	// 						"description":"Color",
	// 						"value":"RED",
	// 						"sequence":3,
	// 						"valueSequence":0
	// 					},
	// 					"Size_Grp_1_P":{  
	// 						"name":"Size_Grp_1_P",
	// 						"description":"Size",
	// 						"value":"XL",
	// 						"sequence":0,
	// 						"valueSequence":6
	// 					}
	// 				},
	// 				"descriptiveAttrs":{  

	// 				},
	// 				"inventory":{  
	// 					"inventoryStatus":"Unavailable",
	// 					"inventory":0,
	// 					"published":true
	// 				},
	// 				"priceFlag":"1"
	// 			},
	// 			{  
	// 				"itemId":"5881667",
	// 				"shortSku":"618965576",
	// 				"longSku":"121-224-0645-200",
	// 				"prodImg":"99553_01",
	// 				"swatchSequence":"01",
	// 				"listPrice":50,
	// 				"listPriceFmt":"$50.00",
	// 				"offerPrice":50,
	// 				"offerPriceFmt":"$50.00",
	// 				"taxItemType":"CLT",
	// 				"definingAttrs":{  
	// 					"Size":{  
	// 						"name":"Size",
	// 						"description":"Size",
	// 						"value":"S",
	// 						"sequence":50,
	// 						"valueSequence":4
	// 					},
	// 					"Color":{  
	// 						"name":"Color",
	// 						"description":"Color",
	// 						"value":"NAVY",
	// 						"sequence":1,
	// 						"valueSequence":0
	// 					},
	// 					"Size_Grp_1_P":{  
	// 						"name":"Size_Grp_1_P",
	// 						"description":"Size",
	// 						"value":"S",
	// 						"sequence":0,
	// 						"valueSequence":3
	// 					}
	// 				},
	// 				"descriptiveAttrs":{  

	// 				},
	// 				"inventory":{  
	// 					"inventoryStatus":"Unavailable",
	// 					"inventory":0,
	// 					"published":true
	// 				},
	// 				"priceFlag":"1"
	// 			},
	// 			{  
	// 				"itemId":"5882100",
	// 				"shortSku":"619246725",
	// 				"longSku":"121-224-0645-500",
	// 				"prodImg":"99553_03",
	// 				"swatchSequence":"03",
	// 				"listPrice":50,
	// 				"listPriceFmt":"$50.00",
	// 				"offerPrice":50,
	// 				"offerPriceFmt":"$50.00",
	// 				"taxItemType":"CLT",
	// 				"definingAttrs":{  
	// 					"Size":{  
	// 						"name":"Size",
	// 						"description":"Size",
	// 						"value":"XS",
	// 						"sequence":30,
	// 						"valueSequence":2
	// 					},
	// 					"Color":{  
	// 						"name":"Color",
	// 						"description":"Color",
	// 						"value":"RED",
	// 						"sequence":3,
	// 						"valueSequence":0
	// 					},
	// 					"Size_Grp_1_P":{  
	// 						"name":"Size_Grp_1_P",
	// 						"description":"Size",
	// 						"value":"XS",
	// 						"sequence":0,
	// 						"valueSequence":2
	// 					}
	// 				},
	// 				"descriptiveAttrs":{  

	// 				},
	// 				"inventory":{  
	// 					"inventoryStatus":"Unavailable",
	// 					"inventory":0,
	// 					"published":true
	// 				},
	// 				"priceFlag":"1"
	// 			},
	// 			{  
	// 				"itemId":"5882101",
	// 				"shortSku":"619246733",
	// 				"longSku":"121-224-0645-200",
	// 				"prodImg":"99553_01",
	// 				"swatchSequence":"01",
	// 				"listPrice":50,
	// 				"listPriceFmt":"$50.00",
	// 				"offerPrice":50,
	// 				"offerPriceFmt":"$50.00",
	// 				"taxItemType":"CLT",
	// 				"definingAttrs":{  
	// 					"Size":{  
	// 						"name":"Size",
	// 						"description":"Size",
	// 						"value":"XS",
	// 						"sequence":30,
	// 						"valueSequence":2
	// 					},
	// 					"Color":{  
	// 						"name":"Color",
	// 						"description":"Color",
	// 						"value":"NAVY",
	// 						"sequence":1,
	// 						"valueSequence":0
	// 					},
	// 					"Size_Grp_1_P":{  
	// 						"name":"Size_Grp_1_P",
	// 						"description":"Size",
	// 						"value":"XS",
	// 						"sequence":0,
	// 						"valueSequence":2
	// 					}
	// 				},
	// 				"descriptiveAttrs":{  

	// 				},
	// 				"inventory":{  
	// 					"inventoryStatus":"Unavailable",
	// 					"inventory":0,
	// 					"published":true
	// 				},
	// 				"priceFlag":"1"
	// 			},
	// 			{  
	// 				"itemId":"5882135",
	// 				"shortSku":"619374583",
	// 				"longSku":"121-224-0645-320",
	// 				"prodImg":"99553_02",
	// 				"swatchSequence":"02",
	// 				"listPrice":50,
	// 				"listPriceFmt":"$50.00",
	// 				"offerPrice":50,
	// 				"offerPriceFmt":"$50.00",
	// 				"taxItemType":"CLT",
	// 				"definingAttrs":{  
	// 					"Size":{  
	// 						"name":"Size",
	// 						"description":"Size",
	// 						"value":"XXL",
	// 						"sequence":150,
	// 						"valueSequence":12
	// 					},
	// 					"Color":{  
	// 						"name":"Color",
	// 						"description":"Color",
	// 						"value":"BLUE",
	// 						"sequence":2,
	// 						"valueSequence":0
	// 					},
	// 					"Size_Grp_1_P":{  
	// 						"name":"Size_Grp_1_P",
	// 						"description":"Size",
	// 						"value":"XXL",
	// 						"sequence":0,
	// 						"valueSequence":7
	// 					}
	// 				},
	// 				"descriptiveAttrs":{  

	// 				},
	// 				"inventory":{  
	// 					"inventoryStatus":"Unavailable",
	// 					"inventory":0,
	// 					"published":true
	// 				},
	// 				"priceFlag":"1"
	// 			},
	// 			{  
	// 				"itemId":"5882136",
	// 				"shortSku":"619374591",
	// 				"longSku":"121-224-0645-320",
	// 				"prodImg":"99553_02",
	// 				"swatchSequence":"02",
	// 				"listPrice":50,
	// 				"listPriceFmt":"$50.00",
	// 				"offerPrice":50,
	// 				"offerPriceFmt":"$50.00",
	// 				"taxItemType":"CLT",
	// 				"definingAttrs":{  
	// 					"Size":{  
	// 						"name":"Size",
	// 						"description":"Size",
	// 						"value":"XS",
	// 						"sequence":30,
	// 						"valueSequence":2
	// 					},
	// 					"Color":{  
	// 						"name":"Color",
	// 						"description":"Color",
	// 						"value":"BLUE",
	// 						"sequence":2,
	// 						"valueSequence":0
	// 					},
	// 					"Size_Grp_1_P":{  
	// 						"name":"Size_Grp_1_P",
	// 						"description":"Size",
	// 						"value":"XS",
	// 						"sequence":0,
	// 						"valueSequence":2
	// 					}
	// 				},
	// 				"descriptiveAttrs":{  

	// 				},
	// 				"inventory":{  
	// 					"inventoryStatus":"Unavailable",
	// 					"inventory":0,
	// 					"published":true
	// 				},
	// 				"priceFlag":"1"
	// 			},
	// 			{  
	// 				"itemId":"5882137",
	// 				"shortSku":"619374604",
	// 				"longSku":"121-224-0645-320",
	// 				"prodImg":"99553_02",
	// 				"swatchSequence":"02",
	// 				"listPrice":50,
	// 				"listPriceFmt":"$50.00",
	// 				"offerPrice":50,
	// 				"offerPriceFmt":"$50.00",
	// 				"taxItemType":"CLT",
	// 				"definingAttrs":{  
	// 					"Size":{  
	// 						"name":"Size",
	// 						"description":"Size",
	// 						"value":"S",
	// 						"sequence":50,
	// 						"valueSequence":4
	// 					},
	// 					"Color":{  
	// 						"name":"Color",
	// 						"description":"Color",
	// 						"value":"BLUE",
	// 						"sequence":2,
	// 						"valueSequence":0
	// 					},
	// 					"Size_Grp_1_P":{  
	// 						"name":"Size_Grp_1_P",
	// 						"description":"Size",
	// 						"value":"S",
	// 						"sequence":0,
	// 						"valueSequence":3
	// 					}
	// 				},
	// 				"descriptiveAttrs":{  

	// 				},
	// 				"inventory":{  
	// 					"inventoryStatus":"Unavailable",
	// 					"inventory":0,
	// 					"published":true
	// 				},
	// 				"priceFlag":"1"
	// 			},
	// 			{  
	// 				"itemId":"5882138",
	// 				"shortSku":"619374612",
	// 				"longSku":"121-224-0645-320",
	// 				"prodImg":"99553_02",
	// 				"swatchSequence":"02",
	// 				"listPrice":50,
	// 				"listPriceFmt":"$50.00",
	// 				"offerPrice":50,
	// 				"offerPriceFmt":"$50.00",
	// 				"taxItemType":"CLT",
	// 				"definingAttrs":{  
	// 					"Size":{  
	// 						"name":"Size",
	// 						"description":"Size",
	// 						"value":"M",
	// 						"sequence":90,
	// 						"valueSequence":6
	// 					},
	// 					"Color":{  
	// 						"name":"Color",
	// 						"description":"Color",
	// 						"value":"BLUE",
	// 						"sequence":2,
	// 						"valueSequence":0
	// 					},
	// 					"Size_Grp_1_P":{  
	// 						"name":"Size_Grp_1_P",
	// 						"description":"Size",
	// 						"value":"M",
	// 						"sequence":0,
	// 						"valueSequence":4
	// 					}
	// 				},
	// 				"descriptiveAttrs":{  

	// 				},
	// 				"inventory":{  
	// 					"inventoryStatus":"Unavailable",
	// 					"inventory":0,
	// 					"published":true
	// 				},
	// 				"priceFlag":"1"
	// 			},
	// 			{  
	// 				"itemId":"5882139",
	// 				"shortSku":"619374621",
	// 				"longSku":"121-224-0645-320",
	// 				"prodImg":"99553_02",
	// 				"swatchSequence":"02",
	// 				"listPrice":50,
	// 				"listPriceFmt":"$50.00",
	// 				"offerPrice":50,
	// 				"offerPriceFmt":"$50.00",
	// 				"taxItemType":"CLT",
	// 				"definingAttrs":{  
	// 					"Size":{  
	// 						"name":"Size",
	// 						"description":"Size",
	// 						"value":"L",
	// 						"sequence":110,
	// 						"valueSequence":8
	// 					},
	// 					"Color":{  
	// 						"name":"Color",
	// 						"description":"Color",
	// 						"value":"BLUE",
	// 						"sequence":2,
	// 						"valueSequence":0
	// 					},
	// 					"Size_Grp_1_P":{  
	// 						"name":"Size_Grp_1_P",
	// 						"description":"Size",
	// 						"value":"L",
	// 						"sequence":0,
	// 						"valueSequence":5
	// 					}
	// 				},
	// 				"descriptiveAttrs":{  

	// 				},
	// 				"inventory":{  
	// 					"inventoryStatus":"Unavailable",
	// 					"inventory":0,
	// 					"published":true
	// 				},
	// 				"priceFlag":"1"
	// 			},
	// 			{  
	// 				"itemId":"5882140",
	// 				"shortSku":"619374639",
	// 				"longSku":"121-224-0645-320",
	// 				"prodImg":"99553_02",
	// 				"swatchSequence":"02",
	// 				"listPrice":50,
	// 				"listPriceFmt":"$50.00",
	// 				"offerPrice":50,
	// 				"offerPriceFmt":"$50.00",
	// 				"taxItemType":"CLT",
	// 				"definingAttrs":{  
	// 					"Size":{  
	// 						"name":"Size",
	// 						"description":"Size",
	// 						"value":"XL",
	// 						"sequence":130,
	// 						"valueSequence":10
	// 					},
	// 					"Color":{  
	// 						"name":"Color",
	// 						"description":"Color",
	// 						"value":"BLUE",
	// 						"sequence":2,
	// 						"valueSequence":0
	// 					},
	// 					"Size_Grp_1_P":{  
	// 						"name":"Size_Grp_1_P",
	// 						"description":"Size",
	// 						"value":"XL",
	// 						"sequence":0,
	// 						"valueSequence":6
	// 					}
	// 				},
	// 				"descriptiveAttrs":{  

	// 				},
	// 				"inventory":{  
	// 					"inventoryStatus":"Unavailable",
	// 					"inventory":0,
	// 					"published":true
	// 				},
	// 				"priceFlag":"1"
	// 			}
	// 		],
	// 		"newArrival":false,
	// 		"maxPurchaseQty":2,
	// 		"loadDate":"2015-10-08T17:46:12"
	// 	};
	// }
});
